# Generated by Django 5.2.7 on 2025-11-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='related_model',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.modeltemplate'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='linked_models',
            field=models.ManyToManyField(blank=True, related_name='chat_sessions', to='api.modeltemplate'),
        ),
    ]
