# Generated by Django 5.2.7 on 2025-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_chatsession_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltemplate',
            name='atom_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modeltemplate',
            name='bond_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
